version: '2'

services:
  reusesocketd:
    image: reusesocketd
    network_mode: "host"
    volumes:
     - shared:/var/shared_run
    restart: always

  jetex:
    image: jetex
    networks:
      - internal
    depends_on:
     - reusesocketd
    volumes:
     - shared:/var/shared_run:ro
     - /tmp/data:/data:ro
    restart: unless-stopped

volumes:
  shared: {}

networks:
  internal: {}
